import type { Metadata } from 'next'
import { Albert_Sans, Kalam, Space_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './navbar'

const albertSans = Albert_Sans({
  subsets: ['latin']
})

export const kalam = Kalam({ 
  weight: ['300', '400', '700'],
  subsets: ['latin'] 
})

export const spaceMono = Space_Mono({
  weight: ['400', '700'],
  style: [ 'italic', 'normal'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Danny Graugnard Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={albertSans.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
